version: "3.8"
services:
    client:
        stdin_open: true
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - "/app/node_modules"
            - "./client:/app"